# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.
# "github" = "ï„“"

fallback_icon = "âŠ "
deduplicate_icons = false
separator = " "

[matching]
"blueman-manager" = "ïŠ“"
"anki" = "A"
"obsidian" = "ğŸª¨"
"packetTracer" = "ğŸ–§"
"dev.zed.Zed" = "ï£¬"
"teams-for-linux" = "ïƒ€"
"alacritty" = "ï„ "
"foot" = "ï„ "
"rust" = "î¨"
"google" = "ï† "
"youtube" = "ï…§"
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"cachy-browser" = "ï‰©"
"chromium" = "ï‰¨"
"thorium-browser" = "ï‰¨"
"thunar" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ï‡‚"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"imv" = "ï€¾"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ï€½"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ï‡"
"evince" = "ïœ¤"
"virt-manager" = "ï ¢"
"audacity" = "ïŸŠ"
"io.github.whoozle.android-file-transfer" = "ï˜Ÿ"
"org.telegram.desktop" = "ï‹†"
"nemo" = "ğŸ“"
"vscodium" = "îœŒ"
"org.manjaro.pamac.manager" = "ï——"
"com.rtosta.zapzap" = "ïˆ²"
"com.ktechpit.whatsie" = "ïˆ²"
"wasistlos" = "ïˆ²"
"io.github.seadve.Kooha" = "âš"
"jetbrains-clion" = "ï‡‹"
"freetube" = "ï…§"
"quran-companion" = "îŠ‹"
"com.github.xournalpp.xournalpp" = "ï„"
"PacketTracer" = "ğŸ–§"
'Bitwarden' = 'ï‚„'
'Thunderbird' = 'ïƒ '
'thunderbird' = 'ïƒ '
'Slack' = 'ï†˜'
'vlc' = 'ï€½'
'discord' = 'ï’'
